### ISSUE TITLE
Getting InvalidInstanceIDNotFound running /opt/mu/lib/test/smoke_test.rb

### ISSUE THREAD

**Issue by cgswong** [cloudamatic/mu#38]
I'm getting the below error stack when running `/opt/mu/lib/test/smoke_test.rb`

```
/opt/rubies/ruby-2.1.6/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.28/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': The instance ID 'i-01d72e2e8d16ad4d0' does not exist (Aws::EC2::Errors::InvalidInstanceIDNotFound)
        from /opt/rubies/ruby-2.1.6/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.28/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
        from /opt/rubies/ruby-2.1.6/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.28/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
        from /opt/rubies/ruby-2.1.6/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.28/lib/seahorse/client/plugins/response_target.rb:21:in `call'
        from /opt/rubies/ruby-2.1.6/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.28/lib/seahorse/client/request.rb:70:in `send_request'
        from /opt/rubies/ruby-2.1.6/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.28/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
        from /opt/mu/lib/modules/mu/clouds/aws.rb:354:in `call'
        from /opt/mu/lib/modules/mu/clouds/aws.rb:354:in `method_missing'
        from /opt/mu/lib/modules/mu.rb:444:in `<module:MU>'
        from /opt/mu/lib/modules/mu.rb:49:in `<top (required)>'
        from /opt/rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/rubies/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/mu/bin/mu-deploy:27:in `<main>'
```

I'm using the new longer format instance ID but the AWS Ruby SDK is compatible so not sure what's happening here. Any thoughts?

**Comment by jstange** [comment]
I'll take a look at this in an account with the new-school instance IDs when I get a minute. Thanks for the report!

**Comment by jstange** [comment]
This one I haven't been able to reproduce, but I'm willing to put a nickel on it being a weird side-effect of #39 . Let me know if the latest commits clear this hurdle.

**Comment by cgswong** [comment]
Looks like it was related to #39
